title: Pilvipalvelut web-kehityksessä
description: Pilvipalvelut web-kehityksessä
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

header_pages:
- index.md
- ./wk2/vko2.md
- ./wk3/vko3.md

github_username: aapokiljunen