title: Pilvipalvelut web-kehityksessä
description: Cloud Services in Web Development website for course assignments
theme: jekyll-theme-cayman

header_pages:
- index.md
- ./wk2/vko2.md
- ./wk3/vko3.md

github_username: aapokiljunen